---
title: "Replicate Concordance"
author: "JL"
date: "7/12/2017"
output: 
  html_document: 
    keep_md: yes
---

TODO 

- manual
- automatic
  - with/without QC
  
1. CV of reps
2. ICC
3. min diff
4. max diff
  
```{r setup,eval=FALSE, include=FALSE}
mets =   read.delim("/Volumes/Beta/data/flow/concordance/all.metrics.txt",stringsAsFactors = FALSE,sep = "\t") 
save(mets,file ="/Volumes/Beta/data/flow/concordance/all.metrics.Rdata" )

```

```{r eval=TRUE, echo=FALSE,warning=FALSE,include=FALSE}
library(knitr)
library(raster)
library("ggplot2")
library(plyr)
theme_set(theme_bw(20))

load("/Volumes/Beta/data/flow/concordance/all.metrics.Rdata")
```

```{r eval=TRUE, echo=FALSE}
map = read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/panel1Map.txt",stringsAsFactors = FALSE,sep = "\t") 

ctrlUse =grepl("_Ctl",mets$name)
metsControls =mets[ctrlUse,]
metsControls$CTRL_NAME = gsub(".*_Ctl","",metsControls$name)
metsControls$CTRL_NAME = gsub("_G","G",metsControls$CTRL_NAME)
metsControls$CTRL_NAME = gsub("_.*","",metsControls$CTRL_NAME)
# kable(as.data.frame(table(metsControls$CTRL_NAME)),format = "markdown")
metsControls$CTRL_NAME = gsub("-","",metsControls$CTRL_NAME)
metsControls$CTRL_NAME = gsub("DHS","",metsControls$CTRL_NAME)
metsControls$CTRL_NAME = gsub("newbiolegend","",metsControls$CTRL_NAME)

metsControlsAuto = metsControls[which(metsControls$GATE=="AUTOMATIC"&metsControls$QC=="FALSE"&(metsControls$Population %in% map$Auto|metsControls$Parent=="root")&metsControls$METRIC=="count"),]
metsControlsAuto = merge(metsControlsAuto,map,by.x = "Population",by.y = "Auto",all.x = TRUE)

metsControlsAuto$Merge=paste(metsControlsAuto$Population,metsControlsAuto$name,sep = "_")
row.names(metsControlsAuto) =metsControlsAuto$Merge

for(pop in unique(map$Auto)) {
  for (sample in unique(metsControlsAuto$name)) {
    row = paste(pop, sample, sep = "_")
    sub = metsControlsAuto[which(metsControlsAuto$Population == pop &
                              metsControlsAuto$name == sample),]
    realParentCount = metsControlsAuto[which(metsControlsAuto$Population == sub$RealAutoParent &
                                          metsControlsAuto$name == sample),]$Count
    lymphCount = metsControlsAuto[which(metsControlsAuto$Population == "lymph" &
                                          metsControlsAuto$name == sample),]$Count
    metsControlsAuto[row, "freqLymph"] = sub$Count / lymphCount

    if (sub$RealAutoParent != "root") {
      metsControlsAuto[row, "freqParent"] = sub$Count / realParentCount

    }else{
      realParentCount = metsControlsAuto[which(metsControlsAuto$Parent == sub$RealAutoParent &
                                          metsControlsAuto$name == sample),]$ParentCount
      metsControlsAuto[row, "freqParent"] = sub$Count / realParentCount

    }
  }
}



metsControlsAuto$GROUP = paste(metsControlsAuto$CTRL_NAME,metsControlsAuto$Population)


# kable(as.data.frame(table(metsControlsAuto$CTRL_NAME)),format = "markdown")
sum =as.data.frame(table(metsControlsAuto[which(metsControlsAuto$Population=="lymph"),]$CTRL_NAME))
colnames(sum) =c("REPLICATE","NUMBER_FCS_FILES")
kable(sum,format = "markdown")




```



Total number of Control fcs files (currently) = `r length(unique(metsControls$name))`

Total number of Control groups (currently) = `r length(unique(metsControls$CTRL_NAME))`

```{r eval=TRUE, echo=FALSE,fig.width=10,fig.height=8,warning=FALSE}


df = data.frame()

for(pop in unique(map$Auto)) {
  for (group in unique(metsControlsAuto$CTRL_NAME)) {
    sub = metsControlsAuto[which(metsControlsAuto$Population == pop &
                              metsControlsAuto$CTRL_NAME == group),]
    # print(paste(pop,group,))
    #     print(paste(pop,group,cv(sub$Count,na.rm = TRUE)))
    tmp = data.frame(
      POP = pop,
      GROUP = group,
      CV_FREQ_PARENT = cv(sub$freqParent,na.rm = TRUE),
      CV_FREQ_LYMPH = cv(sub$freqLymph,na.rm = TRUE)

    )
    df = rbind.data.frame(df, tmp)

  }
}
p <- ggplot(df, aes(x=POP, y=CV_FREQ_PARENT))
p + geom_boxplot() +theme(axis.text.x=element_text(angle=90,hjust=1)) +ylab("CV of Group (freq of parent)")+xlab("population")

p <- ggplot(df, aes(x=POP, y=CV_FREQ_LYMPH))
p + geom_boxplot() +theme(axis.text.x=element_text(angle=90,hjust=1)) +ylab("CV of Group (freq of lymph)")+xlab("population")

```

Percent of parent CV summary

```{r eval=TRUE, echo=FALSE,fig.width=10,fig.height=8,warning=FALSE}
df$GROUP_MEDIAN_CV = df$CV_FREQ_PARENT
df$GROUP_MAD_CV = df$CV_FREQ_PARENT

meds= aggregate(GROUP_MEDIAN_CV ~ GROUP, df, FUN =median,na.action = na.omit)
mads= aggregate(GROUP_MAD_CV ~ GROUP, df, FUN =mad,na.action = na.omit)

kable(merge(meds,mads,by.x = "GROUP",by.y = "GROUP"),format = "markdown")

```


Percent of lymph CV summary

```{r eval=TRUE, echo=FALSE,fig.width=10,fig.height=8,warning=FALSE}
df$GROUP_MEDIAN_CV = df$CV_FREQ_LYMPH
df$GROUP_MAD_CV = df$CV_FREQ_LYMPH

meds= aggregate(GROUP_MEDIAN_CV ~ GROUP, df, FUN =median,na.action = na.omit)
mads= aggregate(GROUP_MAD_CV ~ GROUP, df, FUN =mad,na.action = na.omit)

kable(merge(meds,mads,by.x = "GROUP",by.y = "GROUP"),format = "markdown")

for (group in unique(metsControlsAuto$CTRL_NAME)) {
  sub = metsControlsAuto[which(
  metsControlsAuto$CTRL_NAME == group), ]
  p <- ggplot(sub, aes(x = Population, y = 100*freqParent))+ geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust =
  1)) + ylab("% of parent") + xlab("population") + ggtitle(paste("Ctl",group,"n =",length(unique(sub$name))))
  print(p)
  p <- ggplot(sub, aes(x = Population, y = 100*freqLymph))+ geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust =
  1)) + ylab("% of lymph") + xlab("population") + ggtitle(paste("Ctl",group,"n =",length(unique(sub$name))))
  print(p)
}


library(reshape2)
library(superheat)

metsControlsFilt =metsControlsAuto[which(metsControlsAuto$Population!="boundary"),]
freqpart = dcast(metsControlsFilt,name~Population,value.var ="freqParent" )
row.names(freqpart) = freqpart$name
freqpart =freqpart[,c(-1)]
clustDat = scale(as.matrix(freqpart),center = TRUE,scale = TRUE)
superheat(freqpart, 

          # place dendrograms on columns and rows 
          row.dendrogram = T, 
          col.dendrogram = T,
          
          # make gridlines white for enhanced prettiness
          grid.hline.col = "white",
          grid.vline.col = "white",
          
          # rotate bottom label text
          bottom.label.text.angle = 90)


hlustfunc <- function(x) hclust(x, method="complete")
distfunc <- function(x) as.dist((1-cor(t(x)))/2)
d <- distfunc(clustDat)
fit <- hlustfunc(d)
# plot(fit)

clusterCut <- as.data.frame(cutree(fit, 8))
# clusterCut= clusterCut[order(clusterCut$`cutree(fit, 8)`),] 

kable(clusterCut,format = "markdown")

```