---
title: "ccplus"
author: "JL"
date: "6/2/2017"
output: html_document
---


```{r setup,include=FALSE}
library(ggplot2)
theme_set(theme_bw(20))
library(ConsensusClusterPlus)

options(digits=4)

stab = read.delim("/Users/Kitty/Downloads/P1-P2 HRS pilot2 data-2.csv",stringsAsFactors = FALSE,sep = ",") 
stab$CELLSID =gsub("TCELLS-CD8-NA.*","TCELLS-CD8-NAIVE",stab$CELLSID,fixed = FALSE)
stab$KEY = paste(stab$sample.ID,stab$time.point,stab$CELLSID)
stab$KEY2 = paste(stab$time.point,stab$CELLSID)
stab$sample.ID = as.character(stab$sample.ID)
stab$time.point =gsub("D","",stab$time.point)
stabPBMC = stab[which(stab$SAMPLE.TYPE=="PBMC"),]
stabWB = stab[which(stab$SAMPLE.TYPE=="WB"),]

stabGS = stab[which(stab$SAMPLE.TYPE=="WB"&stab$time.point==0),]

merge =merge(stabPBMC,stabWB,by.x = "KEY",by.y = "KEY")
```


```{r,echo=FALSE}

metrics = data.frame()
sampleBased = data.frame(SAMPLE = as.character(unique(merge$sample.ID.x)))
row.names(sampleBased) = unique(merge$sample.ID.x)

for (type in unique(merge$CELLSID.x)) {
  stabGST = stabGS[which(stabGS$CELLSID == type), ]
  stabGST = stabGST[, c("sample.ID", "CELLS")]
  stabGST$NORM_CELLS = stabGST$CELLS
  # , color=SAMPLE.TYPE.x?
  data = merge[which(merge$CELLSID.x == type), ]
  data = merge(data, stabGST, by.x = "sample.ID.x", by.y = "sample.ID")
  data$L2PBMC = log2(data$CELLS.x / data$NORM_CELLS)
  data$L2PBWB = log2(data$CELLS.y / data$NORM_CELLS)
  
  
  for (tp in unique(data$time.point.x)) {
    current = data[which(data$time.point.x == tp), ]
    sampleTmp = data.frame( DATA = current$CELLS.x)
    colnames(sampleTmp) = c( current$KEY2.x[1])
    row.names(sampleTmp) =current$sample.ID.x
    
    sampleBased = merge(sampleBased, sampleTmp)
    tmp = data.frame(
      TIME = as.numeric(tp),
      TYPE = type,
      L2PBMC_MED = median(current$L2PBMC, na.rm = TRUE),
      SD_L2PBMC = mad(current$L2PBMC, na.rm = TRUE),
      L2PBWB_MED = median(current$L2PBWB, na.rm = TRUE),
      SD_L2PBWB = mad(current$L2PBWB, na.rm = TRUE)
      
    )
    metrics  = rbind(metrics, tmp)
  }
}

results = ConsensusClusterPlus(as.matrix(metrics),maxK=6,reps=50,pItem=0.8,pFeature=1,title=title,clusterAlg="hc",distance="pearson",seed=1262118388.71279,plot="png")

```


## All cell types
```{r,echo=FALSE}
p = ggplot(metrics,aes(x=TIME,y=L2PBMC_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","PBMC"))+ theme(legend.position="none") +ylim(-3,3)
print(p)

p = ggplot(metrics,aes(x=as.numeric(TIME),y=L2PBWB_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","WB"))+ theme(legend.position="none")+ylim(-3,3)
print(p)

```

## with abs median FC to WB 0 >1 
```{r,echo=FALSE}

usePBMC= abs(metrics$L2PBMC_MED)>1
names = metrics[usePBMC,]
usePBMC = metrics$TYPE %in% names$TYPE
usePBMC = metrics[usePBMC,]

useWB= abs(metrics$L2PBWB_MED)>1
names = metrics[useWB,]
useWB = metrics$TYPE %in% names$TYPE
useWB = metrics[useWB,]


p = ggplot(usePBMC,aes(x=as.numeric(TIME),y=L2PBMC_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","PBMC"))+ylim(-3,3)
print(p)

p = ggplot(useWB,aes(x=as.numeric(TIME),y=L2PBWB_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","WB"))+ylim(-3,3)
print(p)

```

# B and T Cells
```{r,echo=FALSE}
p = ggplot(metrics[which(metrics$TYPE=="BCELLS"|metrics$TYPE=="TCELLS"),],aes(x=TIME,y=L2PBMC_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","PBMC"))+ylim(-3,3)
print(p)

p = ggplot(metrics[which(metrics$TYPE=="BCELLS"|metrics$TYPE=="TCELLS"),],aes(x=as.numeric(TIME),y=L2PBWB_MED,color=TYPE))  + geom_line() +xlab("TIME") +ylab("Fold change relative to WB_0")  + labs(title = paste("","WB"))+ylim(-3,3)
print(p)


```

