---
title: "plotTSNE"
author: "JL"
date: "2/15/2017"
output: 
  html_document: 
    keep_md: yes
---
```{r func, eval=TRUE ,echo=FALSE}
library(ggplot2)
run <- function(file, manual,manualRemove) {
require(cytofkit)
require(flowCore)

  #load example fcs, logicle scaling on load
  data_transformed <- cytof_exprsExtract(fcsFile = file, markers = NULL, 
                                         comp = FALSE,
                                         transformMethod = "autoLgcl")
  
  #sub-setting to points that were manually gate already, for comparison
  data_transformed_xk <- data_transformed[ which(!manual$V1 %in% manualRemove), ]
  
  manualUsed = manual[ which(!manual$V1 %in% manualRemove), ]
  ## run PhenoGraph
  cluster_PhenoGraph <- cytof_cluster(xdata = data_transformed_xk, method = "Rphenograph")
  
  # run tsne
  data_transformed_xk_tsne <- cytof_dimReduction(data=data_transformed_xk, method = "tsne")
  
  #combine with original
  data_xk_all <- cbind(data_transformed_xk, data_transformed_xk_tsne, manualUsed,
                       PhenoGraph = cluster_PhenoGraph)
  data_xk_all <- as.data.frame(data_xk_all)
return(data_xk_all)
}

```


## Analysis
```{r analyze, eval=FALSE ,echo=FALSE}
library(cytofkit)
library(flowCore)
file = "~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009.fcs"
manual = read.delim("~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009_coding.xln",header = FALSE)

manualRemove =c(0,1,2,3)# removing these
# subset(dat, hospital %in% goodHosp)
data_xk_all =run(file=file,manual=manual,manualRemove=manualRemove)
save(data_xk_all,file = "~/temp/fcs/testRunDendritic.rdata")

file = "~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009.fcs"
manual = read.delim("~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009_coding.xln",header = FALSE)
manualRemove =c(0)# removing these
# subset(dat, hospital %in% goodHosp)
data_xk_all =run(file=file,manual=manual,manualRemove=manualRemove)
save(data_xk_all,file = "~/temp/fcs/testRunPBMC.rdata")

# cytof_addToFCS(data_xk_all, rawFCSdir=dir, analyzedFCSdir="analysed_FCS", 
#                transformed_cols = c("tsne_1", "tsne_2"), 
#                cluster_cols = c("PhenoGraph", "ClusterX", "FlowSOM"))
```

# Starting from PBMCs, I think

## TSNE results
```{r plot,fig.width=10,fig.height=10,echo=FALSE}
theme_set(theme_bw(20))
load("~/temp/fcs/testRunPBMC.rdata")

mapping = read.delim("~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009_coding_map.txt",header = FALSE)
mapping$code=gsub(".*=", "", mapping$V1, fixed = FALSE)
data_xk_allM  = merge( mapping,data_xk_all, by.x=c("code"),by.y=c("manualUsed"))

ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2)) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, colored by Phenograph clusters detected
```{r plot1,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(PhenoGraph))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, colored by manual gates 
```{r plot2,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(V1))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, Manually gated 
```{r plot4,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(V1))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4))) +facet_wrap(~V1)

```


# Starting from Dendritic, I think

## TSNE results
```{r plot5,fig.width=10,fig.height=10,echo=FALSE}
theme_set(theme_bw(20))
load("~/temp/fcs/testRunDendritic.rdata")

mapping = read.delim("~/temp/fcs/2016-05-20_PANEL 2_ZF_panel 2_F1632217_009_coding_map.txt",header = FALSE)
mapping$code=gsub(".*=", "", mapping$V1, fixed = FALSE)
data_xk_allM  = merge( mapping,data_xk_all, by.x=c("code"),by.y=c("manualUsed"))

ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2)) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, colored by Phenograph clusters detected
```{r plot6,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(PhenoGraph))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, colored by manual gates 
```{r plot7,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(V1))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4)))

```

## TSNE results, Manually gated 
```{r plot8,fig.width=15,fig.height=10,echo=FALSE}
ggplot(data_xk_allM , aes(x = tsne_1,y=tsne_2,color=as.factor(V1))) +geom_point(size = .15)+ guides(colour = guide_legend(override.aes = list(size=4))) +facet_wrap(~V1)

```
