---
title: "Lymph"
author: "JL"
date: "2/17/2017"
output: html_document
---

# 

```{r setup, include=FALSE}
library(openCyto)
library(flowCore)
library(data.table)
library(ggcyto)
library(gridExtra)

```

```{r warning=FALSE,results='hide',echo=FALSE}
theme_set(theme_bw(5))
gt_lymph <-
  gatingTemplate("~/git/auto-fcs/explore/openCyto/lymph.csv", autostart = 1L)
fcsFilesAll <-
  list.files("/Volumes/Beta/data/flow/fcs/",
             pattern = ".fcs",
             full = TRUE)
fcsFilesAll = split(fcsFilesAll, ceiling(seq_along(fcsFilesAll) / 20))
# 4:44

# https://www.bioconductor.org/packages/devel/bioc/vignettes/flowCore/inst/doc/HowTo-flowCore.pdf
i = 1
d = data.frame()
for (files in fcsFilesAll) {
  # fcsFiles = files
  print(files)
  pdf(file = paste("/Volumes/Beta/data/flow/test", i, ".pdf", sep = ""))
  i = i + 1
  for (file in files) {
    print(paste("loading ....", file))
    frame = read.FCS(file)
    print(paste("compensating ....", file))
    
    comp <- compensation(keyword(frame)$`SPILL`)
    
    chnls <- parameters(comp)
    biexpTrans <-
      flowJo_biexp_trans(
        channelRange = 256,
        maxValue = 262144 ,
        pos = 4.418539922,
        neg = 0,
        widthBasis = -100
      )
    tf <- transformerList(chnls, biexpTrans)
    
    print(paste("gating ....", file))
    # gs <- GatingSet(c(new_frame))
    frames = c(frame)
    names(frames) = c(basename(file))
    fs =  as(frames, "flowSet")
    gs1 <- GatingSet(fs)
    gs1 <- compensate(gs1, comp)
    gs1 <- transform(gs1, tf)
    
    gh <- gs1[[1]]
    gating(gt_lymph, gs1)
    print(paste("plotting ....", file))
    
    t1 = ggcyto(gs1,
                mapping = aes(x = "FSC-A", y = "SSC-A"),
                subset = "root") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate() + xlim(c(0, 2e5)) + ylim(c(0, 2e5))
    
    t2 = ggcyto(gs1,
                mapping = aes(x = "FSC-A", y = "SSC-A"),
                subset = "boundary") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate() + xlim(c(0, 2e5)) + ylim(c(0, 2e5))
    
    t3 = ggcyto(gs1,
                mapping = aes(x = "FSC-A", y = "SSC-A"),
                subset = "nonDebris") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate() + xlim(c(0, 2e5)) + ylim(c(0, 2e5))
    
    
    t4 = ggcyto(gs1,
                mapping = aes(x = "FSC-W", y = "FSC-H"),
                subset = "lymph") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate()
    
    t5 = ggcyto(gs1,
                mapping = aes(x = "PE-A", y = "FSC-H"),
                subset = "Singlets") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate()
    
    t6 = ggcyto(gs1,
                mapping = aes(x = "CD3", y = "CD19"),
                subset = "PE-A") +
      geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate()
    
    grid.arrange(
      as.ggplot(t1),
      as.ggplot(t2),
      as.ggplot(t3),
      as.ggplot(t4),
      as.ggplot(t5),
      as.ggplot(t6),
      ncol = 2
    )
    d = rbind.data.frame(as.data.frame(getPopStats(gs1)), d)
  }
  
  dev.off()
}

write.table(
  d,
  sep = "\t",
  quote = FALSE,
  file = "/Volumes/Beta/data/flow/testTypes.txt",
  row.names = FALSE
  )
  # https://github.com/RGLab/openCyto/issues/110

```



