---
title: "openCyto"
author: "JL"
date: "2/16/2017"
output: 
  html_document: 
    keep_md: yes
---

# Notes:

- Testing [openCyto automatic gating](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003806)

- Loosely basing gate strategies off [existing templates](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4748244/)

- Pick your favorite gate strategy for each step in the hierarchy 

- Seems to  mimic manual gating, and results in labelled populations (as opposed to unlabled, like in PhenoGraph)

```{r,eval=TRUE,echo=FALSE,results='hide',include=FALSE,warning=FALSE}
library(openCyto)
library(ggcyto)
# library(ggplot2)
library(flowCore)
ws <- openWorkspace("/Users/Kitty/temp/fcs/513-520 HRS p1&p2.wsp")
fcsFiles <- list.files("/Users/Kitty/temp/fcs/fcsFiles", pattern=".fcs",full = FALSE)
# gs <- parseWorkspace(ws, path = "/Users/Kitty/temp/fcs/fcsFiles", name = 1,subset="2016-05-20_PANEL 1_ZF_panel one_F1631992_004.fcs",isNcdf = FALSE)
gs <- parseWorkspace(ws, path = "/Users/Kitty/temp/fcs/fcsFiles", name = 1,subset=fcsFiles[1:3],isNcdf = FALSE)
# ncfs  <- read.ncdfFlowSet(fcsFiles)
# gs <- GatingSet(ncfs)

```


```{r,echo=FALSE,results='hide',fig.width=10,fig.height=10,warning=FALSE}
# pdf("test.pdf")
# plotGate(gs[[1]],scales=list(cex=c(1.2,1.2)),par.strip.text=list(cex=1.4),xlab=list(fontsize=2),ylab=list(fontsize=2),par.settings=list(gate.text=list(cex=1)),path=1,gpar=list(nrow = 8))
# 
# #  library(gridExtra)
# # grid.arrange(as.ggplot(p2),main="Manual",ncol=2)
# dev.off()
plotGate(gs,getNodes(gs)[39],xbin = 100)
plotGate(gs,getNodes(gs)[10],xbin = 100)

```

```{r,echo=FALSE,results='hide',fig.width=10,fig.height=5,warning=FALSE}
gh <- gs[[1]]
plot(gh)
flowDensityEx <- function(fr, pp_res, channels, ...){
  if(length(channels)==2)
    flowDensity::.flowDensity(fr, pp_res, channels[1], channels[2], ...)
  else
    flowDensity::.flowDensity(fr, pp_res, yChannel = channels, ...)
}
registerPlugins(fun=flowDensityEx,methodName="flowDensity",dep="flowDensity")
# fcs <- read.FCS("~/temp/fcs/fcsFiles/2016-05-20_PANEL 1_ZF_panel one_F1631997_009.fcs", transformation = FALSE)
# autoplot(fcs, x = 'FSC-A', y = 'FSC-H', bins = 64)
# fcs <- read.FCS("~/temp/fcs/fcsFiles/2016-05-20_PANEL 1_ZF_panel one_F1631993_003.fcs", transformation = FALSE)
# fcs@parameters@data
# autoplot(fcs, x = 'FSC-A', y = 'SSC-A', bins = 64)


# Rm("Singlets",gs)
Rm("Lymphocytes (SSC-A v FSC-A)",gs)

# boundary,boundary,root,"FSC-A,SSC-A",boundary,"max=c(2.5e5,2.5e5)",,,,
# Rm("boundary",gs)

template = add_pop(
  gs,
  alias = "boundary",
  pop = "boundary",
  parent = "root",
  dims = "FSC-A,SSC-A",
  gating_method = "boundary",
  gating_args = "min=c(5e4,0),max=c(2.5e5,2.5e5)"
)


ggcyto(gs, mapping = aes(x = `FSC-A`, y = `SSC-A`)) + geom_hex(bins = 100) + geom_gate("boundary") + xlim(c(0, 2e5))
# ggcyto(gs, mapping = aes(x = `FSC-A`, y = `SSC-A`)) + geom_hex(bins = 50) + geom_gate("boundary")+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()


# nonDebris,nonDebris+,boundary,FSC-A,mindensity,"gate_range=c(5e4,1e5),adjust=1.5",,,,
template = rbind(
  template,
  add_pop(
    gs,
    alias = "nonDebris",
    pop = "nonDebris+",
    parent = "boundary",
    dims = "FSC-A",
    gating_method = "mindensity",
    gating_args = "gate_range=c(5e4,1e5),adjust=1.5"

  )
)


ggcyto(gs, mapping = aes(x = `FSC-A`, y = `SSC-A`)) + geom_hex(bins = 100) + geom_gate("nonDebris") + xlim(c(0, 2e5))
ggcyto(gs, mapping = aes(x = `FSC-A`, y = `SSC-A`)) + geom_hex(bins = 100) + geom_gate("nonDebris")+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()

# lymph,lymph,nonDebris,"FSC-A,SSC-A",flowClust,"K=2,quantile=0.95,target=c(1e5,5e4)",,,prior_flowClust,K=2

template = rbind(
  template,
  add_pop(
    gs,
    alias = "lymph",
    pop = "lymph",
    parent = "nonDebris",
    dims = "FSC-A,SSC-A",
    gating_method = "flowClust",
    gating_args = "K=2,quantile=0.95,target=c(1e5,5e4)",
    preprocessing_method = "prior_flowClust",
    preprocessing_args = "K=2"

  )
)


#
# template = rbind(
#     template, add_pop(
#     gs,alias = "lymph",pop = "lymph+",parent = "nonDebris",dims = "FSC-A,SSC-A",gating_method =
#     "flowClust.2d",preprocessing_method = "prior_flowClust",preprocessing_args="K=3",collapseDataForGating = FALSE,gating_args =
#     "quantile=0.95,target=c(80000,50000),K=3"
#     )
#     )

ggcyto(gs,mapping = aes(x = `FSC-A`,y = `SSC-A`)) + geom_hex(bins = 100) + geom_gate("lymph") + xlim(c(0,2e5))
ggcyto(gs,mapping = aes(x = `FSC-A`,y = `SSC-A`)) + geom_hex(bins = 100) + geom_gate("lymph")+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()

template = rbind(
  template,
  add_pop(
    gs,
    alias = "Singlets",
    pop = "FSC-W-",
    parent = "lymph",
    dims = "FSC-W",
    gating_method = "tailgate",
    gating_args =
      "tol=1e-3",
    preprocessing_method = "standardize_flowset"
  )
)
#
#  template = rbind(
#     template, add_pop(
#   gs, alias = "Singlets", pop = "Singlets", parent = "lymph", dims = "FSC-W,FSC-H",gating_method = "singletGate",gating_args =
#   "wider_gate=FALSE,subsample_pct=0.1"
#   )
#  )

 ggcyto(gs, mapping = aes(x = `FSC-W`, y = `FSC-H`)) + geom_hex(bins = 100) + geom_gate("Singlets") + xlim(c(0, 2e5))
  ggcyto(gs, mapping = aes(x = `FSC-W`, y = `FSC-H`)) + geom_hex(bins = 100) + geom_gate("Singlets") + xlim(c(0, 2e5))
#
# template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "Singlets",
#     pop = "Singlets",
#     parent = "lymph",
#     dims = "FSC-H,FSC-W",
#     gating_method = "singletGate",
#     gating_args =
#       "wider_gate=TRUE,subsample_pct=0.1"
#   )
# )
#
# ggcyto(gs,mapping = aes(x = `FSC-H`,y = `FSC-W`)) + geom_hex(bins = 50) + geom_gate("Singlets") + xlim(c(0,2e5))
# ggcyto(gs,mapping = aes(x = `FSC-H`,y = `FSC-W`)) + geom_hex(bins = 50) + geom_gate("Singlets")+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()

# Live	Live-	lymph	Live	cytokine	tol=5e-2		Center	standardize_flowset


# The latest version of OpenCyto contains some changes to the way templates are written for cytokine or tailgate gates. We have moved the preprocessing for tailgate to be explicit. The collapseDataForGating should be set to FALSE and the preprocessing_method should be set to standardize_flowset, in order to get the same behavior as previously by default when collapseDataForGating was set to TRUE.

template = rbind(
  template,
  add_pop(
    gs,
    alias = "PE-A",
    pop = "PE-A-",
    parent = "Singlets",
    dims = "PE-A",
    gating_method = "tailgate",
    gating_args =
      "tol=1e-2",
    preprocessing_method = "standardize_flowset"
  )
)

# ggcyto(gs,mapping = aes(x = `PE-A`,y = `FSC-H`)) + geom_hex(bins = 50) + geom_gate("PE-A") + xlim(c(0,2e5))
ggcyto(gs,mapping = aes(x = `PE-A`,y = `FSC-H`)) + geom_hex(bins = 100) + geom_gate("PE-A")+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()
# Rm("CD3+",gs)
# Rm("CD3-",gs)
template = rbind(
  template,
  add_pop(
    gs,
    alias = "CD3",
    pop = "CD3+/-",
    parent = "PE-A",
    dims = "CD3",
    gating_method = "mindensity",
    gating_args =
      "gate_range=c(80,120)"
  )
)

 ggcyto(gs,mapping = aes(x = "CD3",y = "CD19"),subset = "PE-A") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()

# template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "*",
#     pop = "CD4",
#     parent = "CD3+",
#     dims =  "CD4,CD8",
#     gating_method = "quadGate.tmix",
#     gating_args =
#       "K=4",
#     preprocessing_method = "prior_flowClust",
#     preprocessing_args = "K=4"
#     # preprocessing_args = "K=3"
#   )
# )
 template = rbind(
  template,
  add_pop(
    gs,
    alias = "*",
    pop = "CD4+/-",
    parent = "CD3+",
    dims =  "CD4",
    gating_method = "mindensity"
    # gating_args =
    #   "K=4",
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=4"
    # # preprocessing_args = "K=3"
  )
)
 # CD8-	CD8-	CD3	CD8	mindensity
 template = rbind(
  template,
  add_pop(
    gs,
    alias = "CD8-",
    pop = "CD8-",
    parent = "CD3+",
    dims =  "CD8",
    gating_method = "mindensity"
    # gating_args =
    #   "K=4",
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=4"
    # # preprocessing_args = "K=3"
  )
)

# CD4	CD4+CD8-	CD3	CD4,CD8	refGate	CD4+:CD8-
# CD8	CD4-CD8+	CD3	CD4,CD8	refGate	CD4-:CD8+
  template = rbind(
  template,
  add_pop(
    gs,
    alias = "CD8+",
    pop = "CD8+",
    parent = "CD4-",
    dims =  "CD8",
    gating_method = "mindensity"
    # gating_args =
    #   "K=4",
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=4"
    # # preprocessing_args = "K=3"
  )
)

# CD4	CD4+CD8-	CD3	CD4,CD8	refGate	CD4+:CD8-
  template = rbind(
  template,
  add_pop(
    gs,
    alias = "CD4",
    pop = "CD4+CD8-",
    parent = "CD3+",
    dims =  "CD4,CD8",
    gating_method = "refGate",
    gating_args =
      "CD4+:CD8-"
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=4"
    # # preprocessing_args = "K=3"
  )
)

# CD8	CD4-CD8+	CD3	CD4,CD8	refGate	CD4-:CD8+

 template = rbind(
  template,
  add_pop(
    gs,
    alias = "CD8",
    pop = "CD4-CD8+",
    parent = "CD3+",
    dims =  "CD4,CD8",
    gating_method = "refGate",
    gating_args =
      "CD4-:CD8+"
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=4"
    # # preprocessing_args = "K=3"
  )
)

#  ggcyto(gs,mapping = aes(x = "CD3",y = "CD19"),subset = "PE-A") +
#  geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()
#
# template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "*",
#     pop = "CD4+/-CD8+/-",
#     parent = "CD3+",
#     dims =  "CD4,CD8",
#     gating_method = "mindensity2",
#     gating_args =
#       "gate_range=c(80,220)"
#   )
# )

 ggcyto(gs,mapping = aes(x = "CD4",y = "CD8"),subset = "CD3+") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()
#
  cd4pluscd8minus ="Comp-APC-Cy7-A+Comp-BUV 395-A-"

    cd4minuscd8plus ="Comp-APC-Cy7-A-Comp-BUV 395-A+"
#  template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "CD4_HLADR",
#     pop = "HLADR+",
#     parent ="CD4",
#     dims =  "HLA-DR",
#      gating_method = "tailgate",
#     gating_args =
#       "tol=5e-2",
#     preprocessing_method = "standardize_flowset"
#   )
# )
#
#  ggcyto(gs,
#                 mapping = aes(x = "CD4", y = "HLA-DR"),
#                 subset = "CD4") +
#       geom_hex(bins = 100) + ggcyto_par_set(limits = "data") + geom_gate()
#
 #  ggcyto(gs,mapping = aes(x = "CD4",y = "HLA-DR"),subset = "CD4+CD8-") +
 # geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()


# template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "*",
#     pop = "CD45RA+/-CCR7+/-",
#     parent = "Comp-APC-Cy7-A+Comp-BUV 395-A-",
#     dims =  "CD45RA,CCR7",
#     gating_method = "mindensity2",
#     gating_args =
#       "gate_range=c(80,150)"
#   )
# )

 template = rbind(
  template,
  add_pop(
    gs,
    alias = "*",
    pop = "CD45RA+/-",
    parent = "CD4",
    dims =  "CD45RA",
    gating_method = "mindensity",
    gating_args =
      "gate_range=c(80,150)"
  )
)

ggcyto(gs,mapping = aes(x = "CD45RA",y = "CCR7"),subset = "CD4") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()+ scale_x_flowJo_biexp()+ scale_y_flowJo_biexp()
template = rbind(
  template,
  add_pop(
    gs,
    alias = "CCR7_gate",
    pop = "CCR7",
    parent = "CD4/CD45RA+",
    dims =  "CCR7",
    gating_method = "flowClust",
    gating_args = "K=2",
    preprocessing_method = "prior_flowClust",
    preprocessing_args = "K=2,min=0"
  )
)

ggcyto(gs,mapping = aes(x = "CD45RA",y = "CCR7"),subset = "CD45RA+") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()


template = rbind(
  template,
  add_pop(
    gs,
    alias = "CCR7_gate",
    pop = "CCR7",
    parent = "CD4/CD45RA-",
    dims =  "CCR7",
    gating_method = "flowClust",
    gating_args = "K=2",
    preprocessing_method = "prior_flowClust",
    preprocessing_args = "K=2,min=0"
  )
)

ggcyto(gs,mapping = aes(x = "CD45RA",y = "CCR7"),subset = "CD45RA-") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()

template = rbind(
  template,
  add_pop(
    gs,
    alias = "*",
    pop = "CCR7+/-CD45RA+",
    parent = "CD4",
    dims =  "CCR7,CD45RA",
    gating_method = "refGate",
    gating_args = "CD4/CD45RA+/CCR7_gate:CD4/CD45RA+"
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=2"
  )
)

template = rbind(
  template,
  add_pop(
    gs,
    alias = "*",
    pop = "CCR7+/-CD45RA-",
    parent = "CD4",
    dims =  "CCR7,CD45RA",
    gating_method = "refGate",
    gating_args = "CD4/CD45RA-/CCR7_gate:CD4/CD45RA-"
    # preprocessing_method = "prior_flowClust",
    # preprocessing_args = "K=2"
  )
)


ggcyto(gs,mapping = aes(x = "CD45RA",y = "CCR7"),subset = "CD4") +
 geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()

#
# template = rbind(
#   template,
#   add_pop(
#     gs,
#     alias = "*",
#     pop = "CD95+/-CD28+/-",
#     parent = "CD4+CD8-",
#     dims =  "CD95,CD28",
#     gating_method = "mindensity2",
#     gating_args =
#       "gate_range=c(80,150)"
#   )
# )
#
# ggcyto(gs,mapping = aes(x = "CD95",y = "CD28"),subset = "CD4+CD8-") +
#  geom_hex(bins=100) + ggcyto_par_set(limits = "data") + geom_gate()
#



gh <- gs[[1]]
plot(gh)


```

